name: Web Testing Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # Run daily at 3 AM

jobs:
  web-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [11, 17]
        browser: [chrome, firefox, edge]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up Chrome
      if: matrix.browser == 'chrome'
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
        
    - name: Set up Firefox
      if: matrix.browser == 'firefox'
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest
        
    - name: Set up Edge
      if: matrix.browser == 'edge'
      uses: browser-actions/setup-edge@v1
      with:
        edge-version: latest
        
    - name: Run web tests
      run: mvn clean test -Dbrowser=${{ matrix.browser }}
      
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
        gh_pages: gh-pages
        allure_report: allure-report
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.java-version }}
        path: |
          target/allure-results/
          target/surefire-reports/
          screenshots/
          
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}
        path: screenshots/
        
    - name: Comment PR with test results
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const comment = `## 🌐 Web Test Results
          
          **Browser:** ${{ matrix.browser }}
          **Java Version:** ${{ matrix.java-version }}
          **Status:** ${{ job.status }}
          
          ### Test Summary
          - ✅ All web tests executed successfully
          - 📊 Test reports generated
          - 📸 Screenshots captured on failures
          - 🔍 Cross-browser compatibility verified
          
          **View detailed reports:** [Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/allure-report/)
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
